config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  root 'documents#index'

  resources :documents
end

app/models/document.rb
class Document
  include Mongoid::Document
  include Mongoid::Search
  include Mongoid::Timestamps
  include Mongoid::TagCollectible::Tagged

  TITLE_REGEXP = /^(\s*# )([\wÄÖÜäöüß ]*)(.*)$/
  TAGS_REGEXP = /(#)([\wÄÖÜäöüß]+)/

  field :author, type: String
  field :author_id, type: BSON::ObjectId
  field :folder, type: String
  field :title, type: String
  field :content, type: String
  field :created_at, type: DateTime
  field :updated_at, type: DateTime

  before_save :extract_title
  before_save :extract_tags

  search_in :author, :title, :content

  scope :by_author, ->(author) { where(author_id: author.id) }
  scope :having_text, ->(query) { full_text_search(query) }
  scope :newest_first, -> { order(created_at: "DESC") }


  def extract_title
    return true if content.blank?
    titles = content.lines.map do |line|
      Array(TITLE_REGEXP.match(line))[2]
    end
    self.title ||= titles.compact.first
    true
  end

  def extract_tags
    return true if content.blank?
    extracted_tags = content.lines.map do |line|
      line.scan(TAGS_REGEXP).map { |matches| matches[1] }
    end
    self.tags = extracted_tags.flatten.uniq.map(&:downcase)
    true
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Validatable
  include Clearance::User

  field :email, type: String
  field :encrypted_password, type: String
  field :confirmation_token, type: String
  field :remember_token, type: String
  field :name, type: String

  def self.find_by_email(email)
    User.where(email: email).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :require_login
  before_action :find_document, only: [:show, :edit, :update, :destroy]

  def index
    @documents = search_or_tag
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(author: current_user.name, author_id: current_user.id)
    @document.update(document_params)
    render :show
  end

  def update
    @document.update(document_params)
    render :show
  end

  private

  def document_params
    params.require(:document).permit(:title, :content)
  end

  def find_document
    @document = Document.find(params[:id])
  end

  def search_or_tag
    if(params[:q])
      Document.by_author(current_user).having_text(params[:q]).newest_first
    elsif(params[:t])
      ::DocumentTag.find(params[:t]).tagged.by_author(current_user).newest_first
    else
      Document.by_author(current_user).newest_first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def edit
    user
  end

  def update
    user.update_attributes(profile_params)
    user.save!
    redirect_to root_path
  end

  def validate(record)

  end

  private

  def user
    @user||=User.find(params[:id])
  end

  def profile_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def document_tags
    DocumentTag.order(count: "DESC").limit(5)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/application/_search.html.haml
%h2="Search"
= form_tag(documents_path, method: :get) do
  = text_field_tag :q, params[:q]
  = submit_tag 'Search', name: nil

app/views/application/_tags.html.haml
%h2= "Tags"
%ul
  - document_tags.each do |tag|
    %li= link_to "#{tag.name}(#{tag.count})", documents_path(t: tag.name)

app/views/documents/_document.html.haml
%p
  =link_to "#{document.title} (#{document.created_at})", document_path(document.id)

app/views/documents/_form.html.haml
= simple_form_for @document, :validation => true do |f|
  = f.input :content, as: :text
  %p
    = f.button :submit
    = link_to 'Cancel', :back

app/views/documents/edit.html.haml
%h1
  Edit Document
= render 'form'

app/views/documents/index.html.haml
%h1
  - if params[:q].present?
    = "All documents matching '#{params[:q]}'"
  - elsif params[:t].present?
    = "All documents tagged with '#{params[:t]}'"
  - else
    All documents
= render @documents

app/views/documents/new.html.haml
%h1
  New Document:

= simple_form_for @document, :validation => true do |f|
  = f.input :title
  = f.input :content, as: :text

  %p
    = f.button :submit
    = link_to 'Cancel', :back

app/views/documents/show.html.haml
= button_to "Edit", edit_document_path(@document), method: :get
:markdown
  #{@document.content}

app/views/layouts/_footer.html.haml
%footer#page_footer
  %p &copy; 2015
  %nav
    %ul
      %li Home
      %li About
      %li Terms

app/views/layouts/_header.html.haml
%header#page_header
  = image_tag "http://placehold.it/960x192"
  %h1 blackwell
  %nav
    %ul
      %li
        = link_to "Home", root_path
      - if signed_in?
        %li
          = link_to "Neuer Eintrag", new_document_path
        %li
          = link_to "Alle Einträge", documents_path
        %li
          = link_to current_user.email, edit_user_path(current_user.id)
        %li
          = link_to "Sign out", sign_out_path, method: :delete

      - else
        %li
          = link_to "Sign in", sign_in_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    /
    %title= "blackwell / #{@page_title || 'Home'}"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }

  %body.Blackwell{ :id => params[:controller].parameterize}
    = render 'layouts/header'
    .Blackwell-body
      - flash.each do |name, msg|
        = msg
      %main.Blackwell-content
        = yield
      - if signed_in?
        %nav.Blackwell-nav
          =render "search"
          =render "tags"
    = render 'layouts/footer'

app/views/users/edit.html.haml
%h1
  Edit User:

= simple_form_for @user, :validation => true do |f|
  = f.input :name
  %p
    = f.button :submit
    = link_to 'Cancel', :back